import {  Poppins, PT_Serif} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/blog/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:['200','400','600','800']
});

const pt_serif = PT_Serif({
  variable: "--font-pt_serif",
  subsets: ["latin"],
  weight:['400']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="">
      <body
        className={`${poppins.variable} ${pt_serif.variable} antialiased flex flex-col bg-white w-full min-h-screen `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
