import {  Poppins, PT_Serif} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/blog/Navbar";
import { appProvider } from "@/components/blog/context/AppContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  fallback: ['system-ui', 'arial']
});

const pt_serif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  fallback: ['Georgia', 'serif']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <appProvider>
    <html lang="en" suppressHydrationWarning className="">
      <body
        className={`${poppins.variable} ${pt_serif.variable} antialiased flex flex-col bg-white w-full min-h-screen `}
      >
        <Navbar />
        {children}
      </body>
    </html>
    </appProvider>
  );
}
